# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True, verbose_name='Creation date')),
            ],
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='category',
        ),
        migrations.AddField(
            model_name='cluster',
            name='categories',
            field=models.ManyToManyField(related_name='clusters', to='MainAPP.Category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='MainAPP.Category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='MainAPP.Question', verbose_name='Question'),
        ),
        migrations.AlterField(
            model_name='isometricimage',
            name='cluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isometric_images', to='MainAPP.Cluster', verbose_name='Cluster'),
        ),
        migrations.AddField(
            model_name='selected',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainAPP.Answer'),
        ),
        migrations.AddField(
            model_name='selected',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='users',
            field=models.ManyToManyField(related_name='answers', through='MainAPP.Selected', to=settings.AUTH_USER_MODEL, verbose_name='Selected'),
        ),
    ]
