# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-26 00:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='creation_date',
        ),
        migrations.AddField(
            model_name='position',
            name='edition_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 26, 0, 3, 9, 787771, tzinfo=utc), verbose_name='Last edition date'),
            preserve_default=False,
        ),
    ]
