# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Description'),
        ),
    ]
