# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-20 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0002_question_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='canvas_time',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='poll_time',
            field=models.FloatField(default=0),
        ),
    ]
