# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 17:11
from __future__ import unicode_literals

import MainAPP.hardcode
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0002_auto_20160326_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='Render',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(default='renders/no-img.jpg', upload_to=MainAPP.hardcode.render_image_upload, verbose_name='Rendered Image')),
                ('edition_date', models.DateTimeField(auto_now=True, verbose_name='Last edition date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='render', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Render',
                'verbose_name_plural': 'Renders',
                'permissions': (('query_render', 'Can query Render'), ('list_render', 'Can list Renders')),
            },
        ),
    ]
