# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0003_render'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='style',
            field=models.IntegerField(choices=[(0, 'Radio'), (1, 'Priority')], default=0, verbose_name='Style'),
        ),
    ]
