# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 18:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainAPP', '0004_question_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='selection',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='MainAPP.Question', verbose_name='Question'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='selection',
            name='weight',
            field=models.IntegerField(default=0, verbose_name='Weight'),
            preserve_default=False,
        ),
    ]
